version: 0.2

phases:
  install:
    commands:
      - echo Installation des dependances...

  pre_build:
    commands:
      - echo Connexion ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION |
          docker login --username AWS --password-stdin $ECR_REPO_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)

  build:
    commands:
      - echo Build image Docker pipeline_animation_v2...
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
      - docker tag $ECR_REPO_URI:$IMAGE_TAG $ECR_REPO_URI:latest

  post_build:
    commands:
      - echo Push image vers ECR...
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - docker push $ECR_REPO_URI:latest
      - echo Build termine - image disponible dans ECR
      - printf '[{"name":"vecu-container","imageUri":"%s:%s"}]'
          $ECR_REPO_URI $IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
